# This is a file added by the fork.
# Original author: @USS-Shenzhou, tweaked by SNWCreations

name: Build with Gradle
on:
  push:
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'patches/' # Also consider patch files
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'patches/' # Also consider patch files
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Apply Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: $${{ runner.os }}-gradle
      - name: Get Short Identifier
        uses: iendeavor/shorten-commit-sha@v2.0.0
        id: short-sha
      - name: Get Permission
        run: chmod 777 gradlew
      - name: Build
        id: build
        env:
          VERSION_IDENTIFIER: SNAPSHOT+${{ env.shortened_commit_sha }}
        run: ./gradlew :setup mohistJar :githubActionOutput --stacktrace
      - name: GitHub Action Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.build.outputs.artifact_name}}.dev+${{env.shortened_commit_sha}}
          path: projects/mohist/build/libs/*